// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{

    ui_lockScreen_screen_init();
    ui_clock_screen_init();
    ui_app1_screen_init();
    ui_wifi_screen_init();
    ui_weather_screen_init();
    ui_app2_screen_init();
    // ui_camera_screen_init();
    ui_sd_browser_screen_init();
    ui_bt_screen_init();
    

    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_lockScreen);

}

void ui_destroy(void)
{
    ui_lockScreen_screen_destroy();
    ui_clock_screen_destroy();
    ui_app1_screen_destroy();
    ui_wifi_screen_destroy();
    ui_weather_screen_destroy();
    ui_app2_screen_destroy();
    ui_camera_screen_destroy();
}
