// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"
#include "event.h"
#include "esp_heap_caps.h"
#include <string.h>
#include "nvs_flash.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_lockScreen.h"
#include "screens/ui_clock.h"
#include "screens/ui_app1.h"
#include "screens/ui_wifi.h"
#include "screens/ui_weather.h"
#include "screens/ui_app2.h"
#include "screens/ui_camera.h"
#include "screens/ui_canvas.h"
#include "screens/ui_sd_browser.h"
#include "screens/ui_calender.h"
#include "screens/ui_setting.h"
///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_kikyou_png);    // assets/kikyou.png
LV_IMG_DECLARE(ui_img_clock_hour_png);    // assets/clock_hour.png
LV_IMG_DECLARE(ui_img_clock_min_png);    // assets/clock_min.png
LV_IMG_DECLARE(ui_img_streamlinewifi_png);    // assets/StreamlineWifi.png
LV_IMG_DECLARE(ui_img_bluetooth_png);    // assets/bluetooth.png
LV_IMG_DECLARE(ui_img_music1_png);    // assets/music1.png
LV_IMG_DECLARE(ui_img_weather_png);    // assets/weather.png
LV_IMG_DECLARE(ui_img_1703540290);    // assets/cog-fill.png
LV_IMG_DECLARE(ui_img_file_png);    // assets/file.png
LV_IMG_DECLARE(ui_img_canvas_png);    // assets/canvas.png
LV_IMG_DECLARE(ui_img_computer_png);    // assets/computer.png
LV_IMG_DECLARE(ui_img_hugeiconswifioff02_png);    // assets/HugeiconsWifiOff02.png
LV_IMG_DECLARE(ui_img_return_png);    // assets/return.png
LV_IMG_DECLARE(ui_img_lightrainimage_png);    // assets/lightRainImage.png
LV_IMG_DECLARE(ui_img_cloudyimage2_png);    // assets/cloudyImage2.png
LV_IMG_DECLARE(ui_img_cloudyimage1_png);    // assets/cloudyImage1.png
LV_IMG_DECLARE(ui_img_moderaterainimage_png);    // assets/moderateRainImage.png
LV_IMG_DECLARE(ui_img_heavyrainimage_png);    // assets/heavyRainImage.png
LV_IMG_DECLARE(ui_img_partcloudyimage_png);    // assets/partCloudyImage.png
LV_IMG_DECLARE(ui_img_sunimage_png);    // assets/sunImage.png
LV_IMG_DECLARE(ui_img_camera_png);    // assets/camera.png
LV_IMG_DECLARE(ui_img_calender_png);    // assets/camera.png
LV_IMG_DECLARE(red);    // assets/camera.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
