// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void startWifi(lv_event_t * e)
{
	esp_event_post_to(ui_event_loop_handle,APP_EVENT,APP_WIFI_SCAN_START,NULL,0,portMAX_DELAY);
    ESP_LOGI("ui_event","trigger wifi scan start event ");



}


void shutoffWifi(lv_event_t * e)
{
	esp_event_post_to(ui_event_loop_handle, APP_EVENT, APP_WIFI_CLOSE, NULL, 0, portMAX_DELAY);
    ESP_LOGI("ui_event","trigger wifi close event");



}

//启动摄像头
void startCamera(lv_event_t * e)
{
	esp_event_post_to(ui_event_loop_handle, APP_EVENT, APP_CAMERA_ENTER, NULL, 0, portMAX_DELAY);
	ESP_LOGI("ui_event","trigger camera enter event");
}
