// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_APP1_H
#define UI_APP1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_app1
extern void ui_app1_screen_init(void);
extern void ui_app1_screen_destroy(void);
extern void ui_event_app1(lv_event_t * e);
extern lv_obj_t * ui_app1;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_wifiImage;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_BLImage;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_musicImage;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_WeatherImage;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_SetImage;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_fileImage;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_canvasImage;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_computerImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

