// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_APP2_H
#define UI_APP2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_app2
extern void ui_app2_screen_init(void);
extern void ui_app2_screen_destroy(void);
extern void ui_event_app2(lv_event_t * e);
extern lv_obj_t * ui_app2;
extern void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_cameraImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

