// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_BT_H
#define UI_BT_H

#ifdef __cplusplus
extern "C" {
#endif

extern lv_obj_t *ui_bt;


void ui_bt_screen_init(void);







#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

