// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_BT_H
#define UI_BT_H

#ifdef __cplusplus
extern "C" {
#endif

extern lv_obj_t *ui_bt;

extern uint8_t ui_ble_working;

//play/pause button
extern lv_obj_t *g_btn_play_pause;

extern lv_obj_t *ui_switch2;

void ui_bt_screen_init(void);

void ui_bt_control_init(void);

void ui_bt_control_display_all(void);


void ui_bt_control_hide_all(void);






#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

