// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CAMERA_H
#define UI_CAMERA_H

#ifdef __cplusplus
extern "C" {
#endif


extern void ui_camera_screen_init(void);
extern void ui_camera_screen_destroy(void);
extern lv_obj_t * ui_camera ;
extern lv_obj_t * camera_display ;



#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

