// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_camera = NULL;
lv_obj_t * camera_display = NULL;
lv_obj_t * camera_exit_but = NULL;
// event funtions

void ui_camera_return_event_cb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) 
    {
        ESP_LOGI("ui_camera","change screen tp ui_app2");
        esp_event_post_to(ui_event_loop_handle, APP_EVENT, APP_CAMERA_EXIT, NULL, 0, portMAX_DELAY);
        
        _ui_screen_change(&ui_app2, LV_SCR_LOAD_ANIM_NONE, 150, 0, ui_app2_screen_init);     
        
        if(ui_camera!=NULL)
        {
            lv_obj_del_delayed(ui_camera,300);

            ui_camera=NULL;
            camera_display=NULL;
            camera_exit_but=NULL;

        }
        
    }



}






// build funtions

void ui_camera_screen_init(void)
{

    //screen 创建 
    ui_camera = lv_obj_create(NULL);  
    lv_obj_clear_flag(ui_camera, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
    LV_OBJ_FLAG_SCROLL_CHAIN|LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    
    lv_obj_set_style_bg_color(ui_camera, lv_color_hex(0xffffff), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_camera, 255, LV_PART_MAIN);

    //image
    camera_display = lv_img_create(ui_camera);
    lv_img_set_src(camera_display, NULL);  
    lv_obj_align(camera_display, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_size(camera_display,LV_PCT(100),LV_PCT(100));

    camera_exit_but = lv_img_create(camera_display);
    lv_img_set_src(camera_exit_but, &ui_img_return_png);
    lv_obj_set_width(camera_exit_but, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(camera_exit_but, LV_SIZE_CONTENT);    /// 1
    lv_obj_align(camera_exit_but, LV_ALIGN_TOP_MID, -90, -80);
    lv_obj_add_flag(camera_exit_but, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(camera_exit_but, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                        LV_OBJ_FLAG_SNAPPABLE  | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                        LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_img_set_zoom(camera_exit_but, 50);
    lv_obj_set_style_bg_color(camera_exit_but, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(camera_exit_but, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_img_recolor(camera_exit_but, lv_color_hex(0x000000), LV_PART_MAIN );
    lv_obj_set_style_img_recolor_opa(camera_exit_but, 0, LV_PART_MAIN);

    lv_obj_add_event_cb(camera_exit_but, ui_camera_return_event_cb, LV_EVENT_CLICKED, NULL);    

    ESP_LOGI("ui_camera","post app_camera_enter event");

    esp_event_post_to(ui_event_loop_handle, APP_EVENT, APP_CAMERA_ENTER, NULL, 0, portMAX_DELAY);

}

void ui_camera_screen_destroy(void)
{
    if(ui_camera) lv_obj_del(ui_camera);

    // NULL screen variables
    ui_camera = NULL;

}







