// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_Screen2;
lv_obj_t * ui_clock = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_dot1 = NULL;
lv_obj_t * ui_dot2 = NULL;
lv_obj_t * ui_dot3 = NULL;
lv_obj_t * ui_dot4 = NULL;
lv_obj_t * ui_dot5 = NULL;
lv_obj_t * ui_dot6 = NULL;
lv_obj_t * ui_dot8 = NULL;
lv_obj_t * ui_dot7 = NULL;
lv_obj_t * ui_hour = NULL;
lv_obj_t * ui_min = NULL;
lv_obj_t * ui_clockCenter = NULL;
lv_obj_t * ui_clockNumber12 = NULL;
lv_obj_t * ui_clockNumber6 = NULL;
lv_obj_t * ui_clockNumber9 = NULL;
lv_obj_t * ui_clockNumber3 = NULL;
lv_obj_t * ui_second = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_HourMinuteLabel = NULL;
// event funtions
void ui_event_clock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_app1, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_app1_screen_init);
    }
    else if(event_code == LV_EVENT_GESTURE &&  
                lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) 
    {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_lockScreen, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_lockScreen_screen_init);
    }


}

// build funtions

void ui_clock_screen_init(void)
{
    ui_clock = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_clock, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_clock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_clock);
    lv_obj_set_width(ui_Panel1, 200);
    lv_obj_set_height(ui_Panel1, 200);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 20);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot1 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_dot1, 10);
    lv_obj_set_height(ui_dot1, 10);
    lv_obj_set_x(ui_dot1, -40);
    lv_obj_set_y(ui_dot1, 15);
    lv_obj_set_align(ui_dot1, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_dot1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_dot1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dot1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot2 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_dot2, 10);
    lv_obj_set_height(ui_dot2, 10);
    lv_obj_set_x(ui_dot2, -10);
    lv_obj_set_y(ui_dot2, 50);
    lv_obj_set_align(ui_dot2, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_dot2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_dot2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dot2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dot2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot3 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_dot3, 10);
    lv_obj_set_height(ui_dot3, 10);
    lv_obj_set_x(ui_dot3, 40);
    lv_obj_set_y(ui_dot3, 15);
    lv_obj_clear_flag(ui_dot3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_dot3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dot3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dot3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot4 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_dot4, 10);
    lv_obj_set_height(ui_dot4, 10);
    lv_obj_set_x(ui_dot4, 10);
    lv_obj_set_y(ui_dot4, 50);
    lv_obj_clear_flag(ui_dot4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_dot4, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dot4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dot4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot5 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_dot5, 10);
    lv_obj_set_height(ui_dot5, 10);
    lv_obj_set_x(ui_dot5, 10);
    lv_obj_set_y(ui_dot5, -50);
    lv_obj_set_align(ui_dot5, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_dot5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_dot5, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dot5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dot5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot6 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_dot6, 10);
    lv_obj_set_height(ui_dot6, 10);
    lv_obj_set_x(ui_dot6, 40);
    lv_obj_set_y(ui_dot6, -15);
    lv_obj_set_align(ui_dot6, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_dot6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_dot6, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dot6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dot6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot8 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_dot8, 10);
    lv_obj_set_height(ui_dot8, 10);
    lv_obj_set_x(ui_dot8, -40);
    lv_obj_set_y(ui_dot8, -15);
    lv_obj_set_align(ui_dot8, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_dot8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_dot8, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dot8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dot8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot7 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_dot7, 10);
    lv_obj_set_height(ui_dot7, 10);
    lv_obj_set_x(ui_dot7, -10);
    lv_obj_set_y(ui_dot7, -50);
    lv_obj_set_align(ui_dot7, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_dot7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_dot7, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dot7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dot7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hour = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_hour, &ui_img_clock_hour_png);
    lv_obj_set_width(ui_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_hour, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_hour, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_img_set_zoom(ui_hour, 220);
    lv_obj_set_style_img_recolor(ui_hour, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_min = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_min, &ui_img_clock_min_png);
    lv_obj_set_width(ui_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_min, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_min, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_min, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_min, 900);
    lv_img_set_zoom(ui_min, 200);
    lv_obj_set_style_img_recolor(ui_min, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_min, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clockCenter = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_clockCenter, 8);
    lv_obj_set_height(ui_clockCenter, 8);
    lv_obj_set_align(ui_clockCenter, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_clockCenter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_clockCenter, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_clockCenter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clockCenter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clockCenter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clockCenter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_clockCenter, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clockNumber12 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_clockNumber12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clockNumber12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clockNumber12, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_clockNumber12, "12");
    lv_obj_clear_flag(ui_clockNumber12, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_clockNumber12, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clockNumber6 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_clockNumber6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clockNumber6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clockNumber6, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_clockNumber6, "6");
    lv_obj_clear_flag(ui_clockNumber6, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_clockNumber6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clockNumber9 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_clockNumber9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clockNumber9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clockNumber9, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_clockNumber9, "9");
    lv_obj_clear_flag(ui_clockNumber9, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_clockNumber9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clockNumber3 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_clockNumber3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clockNumber3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clockNumber3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_clockNumber3, "3");
    lv_obj_clear_flag(ui_clockNumber3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_clockNumber3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_second = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_second, &ui_img_clock_min_png);
    lv_obj_set_width(ui_second, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_second, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_second, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_second, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_img_set_angle(ui_second, 1800);
    lv_img_set_zoom(ui_second, 300);
    lv_obj_set_style_img_recolor(ui_second, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_second, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_clock);
    lv_obj_set_width(ui_Panel2, 240);
    lv_obj_set_height(ui_Panel2, 60);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Panel2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourMinuteLabel = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_HourMinuteLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HourMinuteLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HourMinuteLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HourMinuteLabel, "12:30:40");
    lv_obj_set_style_text_color(ui_HourMinuteLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HourMinuteLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HourMinuteLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HourMinuteLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_clock, ui_event_clock, LV_EVENT_ALL, NULL);
    uic_Screen2 = ui_clock;

    if(rtc_local_time_syned_flag)
    {
        esp_event_post_to(ui_event_loop_handle,APP_EVENT, APP_SNTP_REQUEST, NULL,0, portMAX_DELAY);
    }

}

void ui_clock_screen_destroy(void)
{
    if(ui_clock) lv_obj_del(ui_clock);

    // NULL screen variables
    uic_Screen2 = NULL;
    ui_clock = NULL;
    ui_Panel1 = NULL;
    ui_dot1 = NULL;
    ui_dot2 = NULL;
    ui_dot3 = NULL;
    ui_dot4 = NULL;
    ui_dot5 = NULL;
    ui_dot6 = NULL;
    ui_dot8 = NULL;
    ui_dot7 = NULL;
    ui_hour = NULL;
    ui_min = NULL;
    ui_clockCenter = NULL;
    ui_clockNumber12 = NULL;
    ui_clockNumber6 = NULL;
    ui_clockNumber9 = NULL;
    ui_clockNumber3 = NULL;
    ui_second = NULL;
    ui_Panel2 = NULL;
    ui_HourMinuteLabel = NULL;

}
