// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CLOCK_H
#define UI_CLOCK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_clock
extern void ui_clock_screen_init(void);
extern void ui_clock_screen_destroy(void);
extern void ui_event_clock(lv_event_t * e);
extern lv_obj_t * ui_clock;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_dot1;
extern lv_obj_t * ui_dot2;
extern lv_obj_t * ui_dot3;
extern lv_obj_t * ui_dot4;
extern lv_obj_t * ui_dot5;
extern lv_obj_t * ui_dot6;
extern lv_obj_t * ui_dot8;
extern lv_obj_t * ui_dot7;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_min;
extern lv_obj_t * ui_clockCenter;
extern lv_obj_t * ui_clockNumber12;
extern lv_obj_t * ui_clockNumber6;
extern lv_obj_t * ui_clockNumber9;
extern lv_obj_t * ui_clockNumber3;
extern lv_obj_t * ui_second;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_HourMinuteLabel;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

