// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_Screen1;
lv_obj_t * ui_lockScreen = NULL;
lv_obj_t * ui_Image1 = NULL;
// event funtions
void ui_event_lockScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_clock, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_clock_screen_init);
    }
}

// build funtions

void ui_lockScreen_screen_init(void)
{
    ui_lockScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_lockScreen, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lockScreen, lv_color_hex(0xFFFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lockScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_lockScreen);
    lv_img_set_src(ui_Image1, &ui_img_kikyou_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_lockScreen, ui_event_lockScreen, LV_EVENT_ALL, NULL);
    uic_Screen1 = ui_lockScreen;

}

void ui_lockScreen_screen_destroy(void)
{
    if(ui_lockScreen) lv_obj_del(ui_lockScreen);

    // NULL screen variables
    uic_Screen1 = NULL;
    ui_lockScreen = NULL;
    ui_Image1 = NULL;

}
