// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_LOCKSCREEN_H
#define UI_LOCKSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_lockScreen
extern void ui_lockScreen_screen_init(void);
extern void ui_lockScreen_screen_destroy(void);
extern void ui_event_lockScreen(lv_event_t * e);
extern lv_obj_t * ui_lockScreen;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

