// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SETTING_H
#define UI_SETTING_H

#ifdef __cplusplus
extern "C" {
#endif

extern lv_obj_t *ui_setting;


void ui_setting_screen_init(void);






#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

