// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_WIFI_H
#define UI_WIFI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_wifi
extern void ui_wifi_screen_init(void);
extern void ui_wifi_screen_destroy(void);
extern lv_obj_t * ui_wifi;
extern void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_WifiOffImage;
extern lv_obj_t * ui_WIfiOnImage;
extern lv_obj_t * ui_Panel3;
extern void ui_event_Image2(lv_event_t * e);
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

