// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_weather = NULL;

//存放今天天气图片
lv_obj_t * ui_TodayWeaImage = NULL;


lv_obj_t * ui_WeatherPosition = NULL;
lv_obj_t * ui_Temperature = NULL;
lv_obj_t * ui_day1Image = NULL;
lv_obj_t * ui_day2Image = NULL;
lv_obj_t * ui_day3Image = NULL;
lv_obj_t * ui_day1Label = NULL;
lv_obj_t * ui_TodayWeather = NULL;
lv_obj_t * ui_day2Label = NULL;
lv_obj_t * ui_day3Label = NULL;



// event funtions
void ui_event_weather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_app1, LV_SCR_LOAD_ANIM_NONE, 150, 0, &ui_app1_screen_init);

    }
}

// build funtions

void ui_weather_screen_init(void)
{
    ui_weather = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_weather, lv_color_hex(0x607575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_TodayWeaImage = lv_img_create(ui_weather);
    lv_img_set_src(ui_TodayWeaImage, &ui_img_sunimage_png);
    lv_obj_set_width(ui_TodayWeaImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TodayWeaImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TodayWeaImage, 0);
    lv_obj_set_y(ui_TodayWeaImage, -100);
    lv_obj_set_align(ui_TodayWeaImage, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TodayWeaImage, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_img_recolor(ui_TodayWeaImage, lv_color_hex(0x35A6D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_TodayWeaImage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_WeatherPosition = lv_label_create(ui_weather);
    lv_obj_set_width(ui_WeatherPosition, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherPosition, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WeatherPosition, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_WeatherPosition, "wuhan");
    lv_obj_set_style_text_color(ui_WeatherPosition, lv_color_hex(0x111212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherPosition, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherPosition, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature = lv_label_create(ui_weather);
    lv_obj_set_width(ui_Temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature, 0);
    lv_obj_set_y(ui_Temperature, -10);
    lv_obj_set_align(ui_Temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temperature, "35");
    lv_obj_set_style_text_color(ui_Temperature, lv_color_hex(0x111212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temperature, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day1Image = lv_img_create(ui_weather);
    lv_img_set_src(ui_day1Image, &ui_img_partcloudyimage_png);
    lv_obj_set_width(ui_day1Image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day1Image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day1Image, -80);
    lv_obj_set_y(ui_day1Image, 70);
    lv_obj_set_align(ui_day1Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_day1Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_day1Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_day1Image, 70);
    lv_obj_set_style_img_recolor(ui_day1Image, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_day1Image, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day2Image = lv_img_create(ui_weather);
    lv_img_set_src(ui_day2Image, &ui_img_sunimage_png);
    lv_obj_set_width(ui_day2Image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day2Image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day2Image, 0);
    lv_obj_set_y(ui_day2Image, 70);
    lv_obj_set_align(ui_day2Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_day2Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_day2Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_day2Image, 70);

    ui_day3Image = lv_img_create(ui_weather);
    lv_img_set_src(ui_day3Image, &ui_img_cloudyimage1_png);
    lv_obj_set_width(ui_day3Image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day3Image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day3Image, 80);
    lv_obj_set_y(ui_day3Image, 70);
    lv_obj_set_align(ui_day3Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_day3Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_day3Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_day3Image, 70);
    // lv_obj_set_style_img_recolor(ui_day3Image, lv_color_hex(0xA7B1B3), LV_PART_MAIN | LV_STATE_DEFAULT);
                    // lv_obj_set_style_img_recolor_opa(ui_day3Image, 255, LV_PART_MAIN | LV_STATE_DEFAULT);]

    ui_day1Label = lv_label_create(ui_weather);
    lv_obj_set_width(ui_day1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day1Label, -80);
    lv_obj_set_y(ui_day1Label, 100);
    lv_obj_set_align(ui_day1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day1Label, "20-25");
    lv_obj_set_style_text_color(ui_day1Label, lv_color_hex(0x111212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day1Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TodayWeather = lv_label_create(ui_weather);
    lv_obj_set_width(ui_TodayWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TodayWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TodayWeather, 0);
    lv_obj_set_y(ui_TodayWeather, 30);
    lv_obj_set_align(ui_TodayWeather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TodayWeather, "lightrain");
    lv_obj_set_style_text_color(ui_TodayWeather, lv_color_hex(0x111212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TodayWeather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TodayWeather, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day2Label = lv_label_create(ui_weather);
    lv_obj_set_width(ui_day2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day2Label, 0);
    lv_obj_set_y(ui_day2Label, 100);
    lv_obj_set_align(ui_day2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day2Label, "25-30");
    lv_obj_set_style_text_color(ui_day2Label, lv_color_hex(0x111212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day3Label = lv_label_create(ui_weather);
    lv_obj_set_width(ui_day3Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day3Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day3Label, 80);
    lv_obj_set_y(ui_day3Label, 100);
    lv_obj_set_align(ui_day3Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day3Label, "30-35");
    lv_obj_set_style_text_color(ui_day3Label, lv_color_hex(0x111212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day3Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_weather, ui_event_weather, LV_EVENT_ALL, NULL);

}

void ui_weather_screen_destroy(void)
{
    if(ui_weather) lv_obj_del(ui_weather);

    // NULL screen variables
    ui_weather = NULL;

    ui_TodayWeaImage=NULL;


    ui_WeatherPosition = NULL;
    ui_Temperature = NULL;
    ui_day1Image = NULL;
    ui_day2Image = NULL;
    ui_day3Image = NULL;
    ui_day1Label = NULL;
    ui_TodayWeather = NULL;
    ui_day2Label = NULL;
    ui_day3Label = NULL;

}
