// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_WEATHER_H
#define UI_WEATHER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_weather
extern void ui_weather_screen_init(void);
extern void ui_weather_screen_destroy(void);
extern void ui_event_weather(lv_event_t * e);
extern lv_obj_t * ui_weather;

extern lv_obj_t * ui_TodayWeaImage;

extern lv_obj_t * ui_WeatherPosition;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_day1Image;
extern lv_obj_t * ui_day2Image;
extern lv_obj_t * ui_day3Image;
extern lv_obj_t * ui_day1Label;
extern lv_obj_t * ui_TodayWeather;
extern lv_obj_t * ui_day2Label;
extern lv_obj_t * ui_day3Label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

