// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

//wifi state flag , 1 means wifi is working
uint8_t ui_wifi_working;


lv_obj_t * ui_wifi = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_WifiOffImage = NULL;
lv_obj_t * ui_WIfiOnImage = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Image2 = NULL;
// event funtions
void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    //wifi open state
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) 
    {
        //if ble is working ,ignore this request to start wifi
        if(ui_ble_working==1)
        {
            //clear switch check state
            lv_obj_clear_state(target, LV_STATE_CHECKED);

            //disable switch widget until ble stop working
            lv_obj_add_state(target, LV_STATE_DISABLED);

            ui_wifi_working=0;

            return ;
        }

        //if ble is not working ,send wifi start request,change state flag =1
        ui_wifi_working=1;

        startWifi(e);
    }
    //wifi close state
    else if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)==false)
    {
        //remove ble switch's disabled state, allow ble work
        lv_obj_clear_state(ui_switch2, LV_STATE_DISABLED);

        //change flag
        ui_wifi_working=0;

        shutoffWifi(e);


    }
}


void ui_event_Image2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_app1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 150, 0, &ui_app1_screen_init);
    }
}

// build funtions

void ui_wifi_screen_init(void)
{
    //indicate not working
    ui_wifi_working=0;

    ui_wifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_wifi);
    lv_obj_set_width(ui_Switch1, 40);
    lv_obj_set_height(ui_Switch1, 20);
    lv_obj_set_x(ui_Switch1, 85);
    lv_obj_set_y(ui_Switch1, -76);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Switch1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0xA6A6A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiOffImage = lv_img_create(ui_wifi);
    lv_img_set_src(ui_WifiOffImage, &ui_img_hugeiconswifioff02_png);
    lv_obj_set_width(ui_WifiOffImage, 120);
    lv_obj_set_height(ui_WifiOffImage, 100);
    lv_obj_set_x(ui_WifiOffImage, -34);
    lv_obj_set_y(ui_WifiOffImage, 18);
    lv_obj_clear_flag(ui_WifiOffImage, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_img_set_zoom(ui_WifiOffImage, 80);

    ui_WIfiOnImage = lv_img_create(ui_wifi);
    lv_img_set_src(ui_WIfiOnImage, &ui_img_streamlinewifi_png);
    lv_obj_set_width(ui_WIfiOnImage, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_WIfiOnImage, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_WIfiOnImage, -34);
    lv_obj_set_y(ui_WIfiOnImage, 18);
    lv_obj_add_flag(ui_WIfiOnImage, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_WIfiOnImage, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_img_set_zoom(ui_WIfiOnImage, 80);

    ui_Panel3 = lv_obj_create(ui_wifi);
    lv_obj_set_width(ui_Panel3, 240);
    lv_obj_set_height(ui_Panel3, 50);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, -130);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Panel3);
    lv_img_set_src(ui_Image2, &ui_img_return_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -85);
    lv_obj_set_y(ui_Image2, -100);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_img_set_zoom(ui_Image2, 50);
    lv_obj_set_style_bg_color(ui_Image2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Image2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Image2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_Image2, lv_color_hex(0xA6A6A6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_Image2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image2, ui_event_Image2, LV_EVENT_ALL, NULL);

}

void ui_wifi_screen_destroy(void)
{
    if(ui_wifi) lv_obj_del(ui_wifi);

    // NULL screen variables
    ui_wifi = NULL;
    ui_Switch1 = NULL;
    ui_WifiOffImage = NULL;
    ui_WIfiOnImage = NULL;
    ui_Panel3 = NULL;
    ui_Image2 = NULL;

}
